version: '3.8'

services:
  print-color-test:
    image: geertmeersman/print-color-test
    container_name: print-color-test
    environment:
      PRINTER_URI: ipp://10.0.0.24:631/ipp/print
      PRINTER_NAME: Canon GX7050
      EMAIL_FROM: printer@example.com
      EMAIL_TO: you@example.com
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: printer@example.com
      SMTP_PWD: your_app_password
      TELEGRAM_BOT_ID: 123456:ABCDEF
      TELEGRAM_CHAT_ID: -12345678
    ports:
      - "631:631"  # Optional: expose CUPS web interface
    tty: true
